# Generated by Django 2.1.3 on 2019-11-22 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookve_soluong', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dichVu_ten', models.CharField(max_length=50)),
                ('dichVu_gia', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dichvu_anh', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phim_ten', models.CharField(max_length=50)),
                ('phim_nuocphathanh', models.CharField(max_length=50)),
                ('phim_theloai', models.CharField(max_length=50)),
                ('phim_ngayphathanh', models.DateField()),
                ('phim_trangthai', models.CharField(max_length=50)),
                ('phim_trailer', models.FileField(upload_to='video/')),
                ('phim_thongtin', models.TextField()),
                ('anhphim', models.FileField(upload_to='img/')),
                ('rate', models.IntegerField()),
                ('thoiluong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phonenum', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('cmmd', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rap_ten', models.CharField(max_length=50)),
                ('rap_thongtin', models.TextField()),
                ('rap_diachi', models.TextField()),
                ('phims', models.ManyToManyField(blank=True, related_name='phims', to='cinema.Phim')),
            ],
        ),
        migrations.AddField(
            model_name='bookve',
            name='Phims',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Phim'),
        ),
        migrations.AddField(
            model_name='bookve',
            name='bookve_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
