# Generated by Django 2.2.5 on 2019-10-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh_link', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dichVu_ten', models.CharField(max_length=50)),
                ('dichVu_gia', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phim_ten', models.CharField(max_length=50)),
                ('phim_nuocphathanh', models.CharField(max_length=50)),
                ('phim_theloai', models.CharField(max_length=50)),
                ('phim_ngayphathanh', models.DateField()),
                ('phim_trangthai', models.CharField(max_length=50)),
                ('phim_trailer', models.FilePathField(path='/video')),
                ('phim_thongtin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rap_ten', models.CharField(max_length=50)),
                ('rap_thongtin', models.TextField()),
                ('rap_diachi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ve_soluong', models.IntegerField()),
                ('ve_giatien', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ve_ngaychieu', models.DateField()),
                ('ve_phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Phim')),
                ('ve_rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Rap')),
            ],
        ),
        migrations.CreateModel(
            name='BookVe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookve_soluong', models.IntegerField()),
                ('bookve_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookve_ve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Ve')),
            ],
        ),
        migrations.CreateModel(
            name='AnhPhim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anhPhim_anh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Anh')),
                ('anhPhim_phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Phim')),
            ],
        ),
        migrations.CreateModel(
            name='AnhDichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anhDichVu_anh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Anh')),
                ('anhDichVu_dichvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.DichVu')),
            ],
        ),
    ]
