# Generated by Django 2.2.5 on 2019-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phim',
            name='phim_trailer',
            field=models.FilePathField(),
        ),
    ]
