# Generated by Django 2.1.3 on 2019-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anh',
            name='anh_link',
            field=models.CharField(max_length=50),
        ),
    ]
