# Generated by Django 2.2.5 on 2019-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_anhrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anhphim',
            name='anhPhim_anh',
        ),
        migrations.RemoveField(
            model_name='anhphim',
            name='anhPhim_phim',
        ),
        migrations.RemoveField(
            model_name='anhrap',
            name='anhRap_anh',
        ),
        migrations.RemoveField(
            model_name='anhrap',
            name='anhRap_rap',
        ),
        migrations.AddField(
            model_name='rap',
            name='anhs',
            field=models.ManyToManyField(blank=True, related_name='rap_list', to='cinema.Anh'),
        ),
        migrations.DeleteModel(
            name='AnhDichVu',
        ),
        migrations.DeleteModel(
            name='AnhPhim',
        ),
        migrations.DeleteModel(
            name='AnhRap',
        ),
    ]
