# Generated by Django 2.2.5 on 2019-10-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20191026_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phim',
            name='phim_trailer',
            field=models.CharField(max_length=50),
        ),
    ]
