# Generated by Django 2.1.3 on 2019-11-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20191109_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rap_phim_list',
            name='rap_phim_phim',
        ),
        migrations.RemoveField(
            model_name='rap_phim_list',
            name='rap_phim_rap',
        ),
        migrations.AddField(
            model_name='rap',
            name='phims',
            field=models.ManyToManyField(blank=True, related_name='rap_list', to='cinema.Phim'),
        ),
        migrations.DeleteModel(
            name='Rap_phim_list',
        ),
    ]
