# Generated by Django 2.1.3 on 2019-11-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20191110_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rap',
            name='phims',
            field=models.ManyToManyField(blank=True, related_name='phims', to='cinema.Phim'),
        ),
    ]
